"""
run_all_trials.py — robust trial runner for the RCA experiment.

Designed for free-tier Groq: generous timeouts, long gaps between trials
to respect per-minute token limits, natural alarm transitions (no forcing),
and it pauses if it detects rate-limiting so you can swap API keys.

Each trial:
  1. deactivate everything + wait for alarm to be naturally OK  (clean start)
  2. activate the fault (records ground truth)
  3. invoke the target function several times (generate real errors)
  4. wait for the alarm to fire and a NEW diagnosis to be recorded
  5. deactivate the fault
  6. long cool-down before the next trial

USAGE
  # one scenario:
  python3 run_all_trials.py --scenario exception --repeats 5

  # all five scenarios, N each:
  python3 run_all_trials.py --all --repeats 5

  # control (no-fault) runs:
  python3 run_all_trials.py --scenario control --repeats 5

Notes:
  * Base URL for the site is not needed — errors are generated by invoking
    the Lambda directly (more reliable than driving the website).
  * If the RCA Lambda logs an HTTP 429, the runner prints a clear message and
    keeps going; swap to a fresh Groq key when you see repeated 429s.
  * Do NOT clear the DynamoDB tables between scenarios — data accumulates.
    Evaluate once at the very end.
"""

import argparse
import json
import subprocess
import sys
import time
from datetime import datetime

import boto3

REGION = "us-east-1"
cw = boto3.client("cloudwatch", region_name=REGION)
lam = boto3.client("lambda", region_name=REGION)
dynamo = boto3.resource("dynamodb", region_name=REGION)
RESULTS = dynamo.Table("TicketBuddy_RCAResults")
ALARM = "TicketBuddy_ErrorAlarm"
RCA_LOG_GROUP = "/aws/lambda/TicketBuddy_RCA"

# scenario -> (target function, invoke payload)
SCENARIOS = {
    "exception": ("TicketBuddy_BookTicket", {"username": "test"}),
    "timeout": ("TicketBuddy_BookTicket", {"username": "test"}),
    "cpu_overload": ("TicketBuddy_GetSchedules", {"from": "Dublin", "to": "Cork"}),
    "dynamodb_failure": ("TicketBuddy_GetSchedules", {"from": "Dublin", "to": "Cork"}),
    "api_failure": ("TicketBuddy_TaxCalculator", {"price": 50, "country_code": "IE"}),
}
ALL_TARGETS = list({v[0] for v in SCENARIOS.values()})

# --- generous timing (seconds) ---
INVOKE_COUNT = 6          # invocations per trial (>=6 reliably trips the alarm)
INVOKE_GAP = 3            # gap between invocations
ALARM_OK_TIMEOUT = 300    # max wait for the alarm to return to OK
RESULT_TIMEOUT = 600      # max wait for a diagnosis after generating errors
INTER_TRIAL_GAP = 120     # cool-down between trials (token-limit safety)
POLL = 10                 # polling interval


def log(m):
    print("[" + datetime.now().strftime("%H:%M:%S") + "] " + m, flush=True)


def run_cli(args):
    r = subprocess.run([sys.executable] + args, capture_output=True, text=True)
    if r.returncode != 0 and r.stderr:
        last = r.stderr.strip().splitlines()[-1] if r.stderr.strip() else ""
        log("  ! " + last[:200])
    return r


def deactivate_all():
    for t in ALL_TARGETS:
        run_cli(["inject_fault.py", "deactivate", "--target", t])


def alarm_state():
    r = cw.describe_alarms(AlarmNames=[ALARM])
    a = r.get("MetricAlarms", [])
    return a[0]["StateValue"] if a else "UNKNOWN"


def wait_for_ok(timeout=ALARM_OK_TIMEOUT):
    """Wait for the alarm to NATURALLY return to OK (do not force it)."""
    log("waiting for alarm to be OK ...")
    deadline = time.time() + timeout
    while time.time() < deadline:
        if alarm_state() == "OK":
            log("alarm is OK")
            return True
        time.sleep(POLL)
    log("alarm still not OK after timeout; proceeding cautiously")
    return False


def count_results():
    return RESULTS.scan(Select="COUNT")["Count"]


def invoke_target(fn, payload, n=INVOKE_COUNT):
    log("generating errors: invoking " + fn + " x" + str(n))
    for i in range(n):
        try:
            lam.invoke(
                FunctionName=fn,
                InvocationType="Event",
                Payload=json.dumps(payload).encode(),
            )
        except Exception as e:
            log("  invoke error: " + str(e)[:120])
        time.sleep(INVOKE_GAP)


def check_recent_429():
    """Look at the RCA log tail for a recent 429 (rate limit)."""
    try:
        logs = boto3.client("logs", region_name=REGION)
        streams = logs.describe_log_streams(
            logGroupName=RCA_LOG_GROUP, orderBy="LastEventTime",
            descending=True, limit=1).get("logStreams", [])
        if not streams:
            return False
        ev = logs.get_log_events(
            logGroupName=RCA_LOG_GROUP,
            logStreamName=streams[0]["logStreamName"],
            limit=15, startFromHead=False).get("events", [])
        return any("429" in e.get("message", "") for e in ev)
    except Exception:
        return False


def wait_for_new_result(baseline, timeout=RESULT_TIMEOUT):
    log("waiting for RCA diagnosis (up to " + str(timeout) + "s) ...")
    deadline = time.time() + timeout
    while time.time() < deadline:
        if count_results() > baseline:
            log("diagnosis recorded")
            return True
        time.sleep(POLL)
    # timed out — check whether it was a rate-limit
    if check_recent_429():
        log("*** RATE LIMITED (HTTP 429) — swap to a fresh Groq key! ***")
    else:
        log("no diagnosis within timeout (alarm may not have fired)")
    return False


def activate(scenario, target, intensity):
    args = ["inject_fault.py", "activate", "--target", target,
            "--type", scenario]
    if intensity:
        args += ["--intensity", str(intensity)]
    run_cli(args)


def one_trial(scenario, intensity, n, total):
    log("===== trial " + str(n) + "/" + str(total)
        + "  scenario=" + scenario + " =====")

    deactivate_all()
    wait_for_ok()

    if scenario == "control":
        run_cli(["inject_fault.py", "control", "--minutes", "2"])
        baseline = count_results()
        # no fault; just wait and see if anything (falsely) fires
        time.sleep(120)
        fp = count_results() - baseline
        log("control done — false positives this window: " + str(fp))
        time.sleep(INTER_TRIAL_GAP)
        return

    target, payload = SCENARIOS[scenario]
    baseline = count_results()

    activate(scenario, target, intensity)
    invoke_target(target, payload)
    wait_for_new_result(baseline)
    deactivate_all()

    log("trial " + str(n) + " done; cooling down "
        + str(INTER_TRIAL_GAP) + "s before next")
    time.sleep(INTER_TRIAL_GAP)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--scenario", choices=list(SCENARIOS) + ["control"])
    p.add_argument("--all", action="store_true",
                   help="run all five fault scenarios")
    p.add_argument("--repeats", type=int, default=5)
    p.add_argument("--intensity", type=int, default=30)
    args = p.parse_args()

    if args.all:
        plan = []
        for r in range(args.repeats):
            for sc in SCENARIOS:
                plan.append(sc)
    elif args.scenario:
        plan = [args.scenario] * args.repeats
    else:
        p.error("give --scenario X or --all")

    total = len(plan)
    log("STARTING EXPERIMENT: " + str(total) + " trials")
    log("(interleaved)" if args.all else "(single scenario)")
    start = time.time()

    for i, sc in enumerate(plan, 1):
        try:
            one_trial(sc, args.intensity, i, total)
        except KeyboardInterrupt:
            log("interrupted — deactivating all faults")
            deactivate_all()
            sys.exit(1)
        except Exception as e:
            log("trial " + str(i) + " error: " + str(e)[:150]
                + " — deactivating and continuing")
            deactivate_all()
            time.sleep(30)

    mins = round((time.time() - start) / 60, 1)
    log("EXPERIMENT COMPLETE: " + str(total) + " trials in " + str(mins) + " min")
    log("Now run:  cd ../evaluation && python3 evaluate_results.py")


if __name__ == "__main__":
    main()